.apex/unpackaged/objects/Mix__c.object
<CustomObject>
    <description>A custom collection of tracks for a customer that will be pressed onto vinyl.</description>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Song__c.object
<CustomObject>
    <description>An instance of a song.</description>
    <fields>
        <fullName>Genre__c</fullName>
        <description>Genre of the song.</description>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>Folk</fullName>
                </value>
                <value>
                    <fullName>Hip hop</fullName>
                </value>
                <value>
                    <fullName>Indy</fullName>
                </value>
                <value>
                    <fullName>Jazz</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Pop</fullName>
                </value>
                <value>
                    <fullName>Rap</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_m__c</fullName>
        <description>Length of the song in minutes.</description>
        <label>Length</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Track_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of times a song is used as a track.</description>
        <label>Track Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Track_Licenses__c</fullName>
        <label>Track Licenses</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Track__c.object
<CustomObject>
    <description>An individual song that is part of a mix.</description>
    <fields>
        <fullName>Mix__c</fullName>
        <description>Mix this track is part of.</description>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Song for this track.</description>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/SongService.cls
/**
 * Created by HP on 22.11.2017.
 */
public class SongService
{
	public static void recalculateTrCount (Map<Id,Song__c> mapSong, Map<Id, Track__c> newMap)
		{
			for (Song__c song : mapSong.values())
				{
					Integer trackCount = song.Tracks__r.size();
					Integer trackLicence = (Integer)song.Track_Licenses__c;
					if(trackCount > trackLicence)
					{
						for (Track__c track : song.Tracks__r )
							{
								Track__c  triggerContextTrack = newMap.get(track.Id);
								if ( triggerContextTrack != null)
								{
									System.debug('Errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrror');
									triggerContextTrack.addError('You exeeded the limits of using that song.');
								}
							}
					} else
					{
						song.Track_Count__c = trackCount;
					}
				}
			update mapSong.values();
		}

	public static Map<Id, Song__c> getRelatedSongs (Set<Id> relatedSongsID)
	{
		Map<Id,Song__c> relatedSongs = new Map <Id,Song__c> ([SELECT name,Genre__c, Track_Count__c, Track_Licenses__c,
				(SELECT  Name,Song__c
						FROM  Tracks__r)
				FROM  Song__c
				WHERE Id in : relatedSongsID]);
		return relatedSongs;
	}
	public static Set<Id> getUsedSongId (Id mixId){
		Set<Id> songId = new Set<Id>();
		List <Track__c> usedTrack = [SELECT Mix__c, Song__r.Id
		                             FROM Track__c
		                             where Mix__c = :mixID];
		for (Track__c track : usedTrack){
			songId.add(track.Song__r.Id);
		}
		return  songID;
	}
	public static Double getLengthOfSongs(Set<Id> songId){
		if (songId.size() == 0){
			return 0;
		}
		AggregateResult aggregateResult = [SELECT  SUM(Length_m__c) sum
		                                   FROM Song__c
		                                   WHERE Id in :songId];
		Double result = (Double) aggregateResult.get('sum');
		return result;
	}



}