.apex/unpackaged/objects/Mix__c.object
<CustomObject>
    <description>A custom collection of tracks for a customer that will be pressed onto vinyl.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact purchasing the mix.</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mixes</relationshipLabel>
        <relationshipName>Mixes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Genre__c</fullName>
        <description>Primary genre of the mix.</description>
        <label>Primary Genre</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Genre__c</fullName>
        <description>Secondary genre of the mix.</description>
        <label>Secondary Genre</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Song__c.object
<CustomObject>
    <description>An instance of a song.</description>
    <fields>
        <fullName>Genre__c</fullName>
        <description>Genre of the song.</description>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>Folk</fullName>
                </value>
                <value>
                    <fullName>Hip hop</fullName>
                </value>
                <value>
                    <fullName>Indy</fullName>
                </value>
                <value>
                    <fullName>Jazz</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Pop</fullName>
                </value>
                <value>
                    <fullName>Rap</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_m__c</fullName>
        <description>Length of the song in minutes.</description>
        <label>Length</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Track__c.object
<CustomObject>
    <description>An individual song that is part of a mix.</description>
    <fields>
        <fullName>Mix__c</fullName>
        <description>Mix this track is part of.</description>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Song for this track.</description>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/MixService.cls
/**
 * Created by HP on 22.11.2017.
 */
public class MixService
{
    public static void setGenre(Map<Id, Mix__c> mapMix )
    {
        for (Mix__c mix : mapMix.values())
        {
            mix.Secondary_Genre__c = null;
            mix.Primary_Genre__c = null;
        }
        system.debug(mapMix);
        AggregateResult [] aggregateResult = [SELECT count(Id) number, Mix__c mixId, Song__r.Genre__c genre
                                              FROM Track__c
                                              WHERE Mix__C in :mapMix.keySet()
                                              GROUP BY Song__r.Genre__c, Mix__c
                                              ORDER BY Mix__c, count(Id) DESC, Song__r.Genre__c];
        System.debug(aggregateResult);

        Id processingMixId;
        for (Integer i=0; i<aggregateResult.size();i++)     // take two first record for every Mix
        {
            if(processingMixId != aggregateResult[i].get('MixId'))
            {
                processingMixId = (Id)aggregateResult[i].get('MixId');
                Mix__c processingMix = mapMix.get(processingMixId);
                if(i+1 < aggregateResult.size() &&  processingMixId == aggregateResult[i+1].get('mixId') )
                {
                    processingMix.Primary_Genre__c = (String)aggregateResult[i].get('genre');
                    i++;
                    processingMix.Secondary_Genre__c = (String)aggregateResult[i].get('genre');
                    system.debug(processingMix);
                    continue;
                }else
                {
                    processingMix.Primary_Genre__c = (String)aggregateResult[i].get('genre');
                    processingMix.Secondary_Genre__c = null;
                    system.debug('norm');
                    continue;
                }
            } else
            {
                continue;
            }
        }
        update mapMix.values();
    }
    public static Map<Id, Mix__c> getRelatedMixes (Set <Id> mixIds )
    {
        Map <Id, Mix__c> mapMix = new Map<Id, Mix__c>([SELECT  Name, Primary_Genre__c, Secondary_Genre__c
                FROM  Mix__c
                WHERE id in :mixIds]);
        return  mapMix;
    }
    public static Integer  getNumOfTracks(Id mixID){
		AggregateResult aggregateResult = [SELECT Mix__c, COUNT(id) number
				FROM Track__c
				WHERE  Mix__c = :mixId
		GROUP BY Mix__c
		LIMIT 1];
		Integer result = (Integer)aggregateResult.get('number');
		return result;
	}
	public static Double getLengthOfMix(Id mixID ){
		AggregateResult  aggregateResults = [SELECT Mix__c, SUM(Song__r.Length_m__c) sum
				FROM Track__c
				WHERE Mix__c = :mixID
		GROUP BY Mix__c
		LIMIT 1];
		Double result = (Double)aggregateResults.get('sum');
		return result;
	}
	public static Mix__c getMixById (Id mixID){
		Mix__c mix = [SELECT Name,Primary_Genre__c,Secondary_Genre__c, Customer__c,
				            ( SELECT name,Song__c
						    FROM Tracks__r)
				      FROM Mix__c
				      Where Id = :mixId
		              Limit 1];
		return mix;
	}

}