.apex/unpackaged/objects/Mix__c.object
<CustomObject>
    <description>A custom collection of tracks for a customer that will be pressed onto vinyl.</description>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Song__c.object
<CustomObject>
    <description>An instance of a song.</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Track__c.object
<CustomObject>
    <description>An individual song that is part of a mix.</description>
    <fields>
        <fullName>Mix__c</fullName>
        <description>Mix this track is part of.</description>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Song for this track.</description>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/unpackaged/classes/MixHandler.cls
/**
 * Created by HP on 22.11.2017.
 */
public class MixHandler implements  TriggerTemplate.Handler
{
    private List<Mix__c> newValues;
    private List<Mix__c> oldValues;
    private Map<Id, Mix__c> oldMap;
    private Map<Id, Mix__c> newMap;

    public  void setValues (List<sObject> newValues, List<sObject> oldValues, Map<Id,sObject> newMap ,Map<Id,sObject> oldMap)
    {
        this.newValues = newValues;
        this.oldValues = oldValues;
        this.oldMap = (Map<Id, Mix__c>) oldMap;
    }
    
    public void handle (TriggerTemplate.TriggerAction action) 
    {
        if (action == TriggerTemplate.TriggerAction.afterDelete)
        {
            List<Track__c> relatedTracks = TrackService.getRelatedTrack(oldValues);
			Map<Id,Track__c> relatedTracksMap = new Map<Id, Track__c>(relatedTracks);
			Set <Id> songIds = Utils.getParentIds(relatedTracks, 'Song__c');
			Map<Id,Song__c> relatedSongs = SongService.getRelatedSongs(songIDs);
			SongService.recalculateTrCount(relatedSongs, relatedTracksMap);
        }
        if (action == TriggerTemplate.TriggerAction.afterUndelete)
        {
			List<Track__c> relatedTracks = TrackService.getRelatedTrack(newValues);
			Map<Id,Track__c> relatedTracksMap = new Map<Id, Track__c>(relatedTracks);
			Set <Id> songIds = Utils.getParentIds(relatedTracks, 'Song__c');
			Map<Id,Song__c> relatedSongs = SongService.getRelatedSongs(songIDs);
			SongService.recalculateTrCount(relatedSongs, relatedTracksMap);

        }
    }
}