.apex/unpackaged/objects/Mix__c.object
<CustomObject>
    <description>A custom collection of tracks for a customer that will be pressed onto vinyl.</description>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

.apex/unpackaged/objects/Song__c.object
<CustomObject>
    <description>An instance of a song.</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Track__c.object
<CustomObject>
    <description>An individual song that is part of a mix.</description>
    <fields>
        <fullName>Mix__c</fullName>
        <description>Mix this track is part of.</description>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Song for this track.</description>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/unpackaged/classes/TrackHandler.cls
public without sharing class TrackHandler implements TriggerTemplate.Handler
{
	private List<Track__c> newValues;
	private List<Track__c> oldValues;
	private Map<Id, Track__c> oldMap;
	private Map<Id, Track__c> newMap;

	public void setValues(List<sObject> newValues, List<sObject> oldValues, Map<Id,sObject> newMap ,Map<Id, sObject> oldMap)
	{
			this.newValues = newValues;
			this.oldValues = oldValues;
		    this.newMap = (Map<Id,Track__c>)newMap;
			this.oldMap = (Map<Id, Track__c>)oldMap;
	}

	public void handle(TriggerTemplate.TriggerAction action)
    {
			if (action == TriggerTemplate.TriggerAction.afterUpdate)
			{
				List<Track__c> modSongIdTracks = Utils.getModifiedObjects(new List<String>{'Song__c'},
						newValues,oldValues);
				Set <Id> songIds = Utils.getParentIds(modSongIdTracks, 'Song__c');
				Map<Id,Song__c> relatedSongs = SongService.getRelatedSongs(songIDs);
				SongService.recalculateTrCount(relatedSongs,newMap);
				Set <Id> mixIds = Utils.getParentIds(modSongIdTracks,'Mix__c');
				Map <Id, Mix__c> mapMix = MixService.getRelatedMixes(mixIDs);
				MixService.setGenre(mapMix);
			}

			if (action == TriggerTemplate.TriggerAction.afterInsert)
			{
				Set <Id> songIds = Utils.getParentIds(newValues, 'Song__c');
				Map<Id,Song__c> relatedSongs = SongService.getRelatedSongs(songIDs);
				SongService.recalculateTrCount(relatedSongs,newMap);
				Set <Id> mixIds = Utils.getParentIds(newValues,'Mix__c');
				Map <Id, Mix__c> mapMix = MixService.getRelatedMixes(mixIDs);
				MixService.setGenre(mapMix);
			}

			if (action == TriggerTemplate.TriggerAction.afterUndelete)
			{
				Set <Id> songIds = Utils.getParentIds(newValues, 'Song__c');
				Map<Id,Song__c> relatedSongs = SongService.getRelatedSongs(songIDs);
				SongService.recalculateTrCount(relatedSongs,newMap);
				Set <Id> mixIds = Utils.getParentIds(newValues,'Mix__c');
				Map <Id, Mix__c> mapMix = MixService.getRelatedMixes(mixIDs);
				MixService.setGenre(mapMix);
			}
			if (action == TriggerTemplate.TriggerAction.afterDelete)
            {
				Set <Id> songIds = Utils.getParentIds(oldValues, 'Song__c');
				Map<Id,Song__c> relatedSongs = SongService.getRelatedSongs(songIDs);
				SongService.recalculateTrCount(relatedSongs,newMap);
				Set <Id> mixIds = Utils.getParentIds(oldValues,'Mix__c');
				Map <Id, Mix__c> mapMix = MixService.getRelatedMixes(mixIDs);
				MixService.setGenre(mapMix);
			}
		}
}