unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Income__c</fullName>
        <label>Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Percentage__c</fullName>
        <label>Tax Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/AssignNewOwner.cls
global class AssignNewOwner implements Database.Batchable<sObject>  {
   
    global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator([SELECT name, Tax_Percentage__c,Payment_Amount__c FROM Order__c]);
   }

   global void execute(Database.BatchableContext BC, List<sObject> scope){
     
       for (sObject obj : scope){
           Order__c order = (Order__c) obj; 
           order.Tax_Percentage__c = 3 ;
           order.Tax_Amount__c = 0.03 * order.Payment_Amount__c;
           order.Income__c = order.Payment_Amount__c  *  0.97; 
       }
       update scope;
    }

   global void finish(Database.BatchableContext BC){
   }
    

}