unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Income__c</fullName>
        <label>Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Percentage__c</fullName>
        <label>Tax Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/classes/OrderService.cls
/**
 * Created by HP on 04.12.2017.
 */
public class OrderService {

    public static void setTax (List<Order__c> orders)
    {
        List<Order__c> result = new List<Order__C>();
        for (Order__c order : orders)
        {
            if(order.Payment_Type__c == 'Cash')
            {
                order.Tax_Percentage__c = 5;
                order.Tax_Amount__c = order.Payment_Amount__c * 0.05;

            }else if (order.Payment_Type__c == 'Credit Card')
            {
                order.Tax_Percentage__c = 5.5;
                order.Tax_Amount__c = order.Payment_Amount__c * 0.055;
            }else if (order.Payment_Type__c == 'Check' )
            {
                order.Tax_Percentage__c = 7;
                order.Tax_Amount__c = order.Payment_Amount__c * 0.07;
            }
            result.add(order);
        }
    }
    public static void setIncome (List<Order__c> orders)
    {
        List<Order__c> result = new List<Order__C>();
        for(Order__c order : orders)
        {
            order.Income__c = order.Payment_Amount__c - order.Tax_Amount__c;
            result.add(order);
        }
    }

}