unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TaskService.cls
/**
 * Created by HP on 04.12.2017.
 */
public class TaskService {

    public static void createTask(List<Order__c> orders)
    {
        List<Task> relatedTasks = new List<Task> ();
        for(Order__c order : orders)
            {
                Task relTask = new Task (Priority = 'High', Status = 'Not Started',
                        Subject = 'Prepare Order - ' + order.Name,
                        OwnerId  = System.UserInfo.getUserId(),
                        Description = order.Description__c
                        );
                relatedTasks.add(relTask);

            }
       insert relatedTasks;
    }
}